### PR TITLE
Updating numbering throughout, and rearranging code accordingly

### PR DESCRIPTION
**Pull request by joeldenning**
So now the specification numbers are correct and the code is in the file in the same order as the specification. I put in some TODOs for some things that have changed in the spec, as well.

### CODE REVIEW

**Comment by guybedford** [comment]
Amazing thank you! Can you update the diff to remove the `dist` changes? The tests should still build fine.

**Comment by guybedford** [comment]
:+1: for merge.

**Comment by joeldenning** [comment]
Just removed the changes to the dist files. But doesn't that mean that the tests will not actually be testing the source code?? Do you usually only update the dist files when releasing?

**Comment by guybedford** [comment]
Yes exactly, typically only builds are done for releases. The tests run the build first at https://github.com/ModuleLoader/es6-module-loader/blob/master/.travis.yml#L35.

**Pull request merged**
