### PR TITLE
chore(travis): test on nodejs 0.12

### PR DESCRIPTION
**Pull request by douglasduteil**

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks!!

**Comment by guybedford** [comment]
@douglasduteil do you have any idea why these credentials might be failing?

**Comment by douglasduteil** [comment]
Hum... I don't think PRs can use **your** Travis Environment Variables.
It's like a "security feature" so not official contributes can't log them

**Comment by guybedford** [comment]
Yeah the strange thing is that it is working for Chrome and Firefox (https://travis-ci.org/ModuleLoader/es6-module-loader/jobs/50178078#L495), just not IE8 (https://travis-ci.org/ModuleLoader/es6-module-loader/jobs/50178079#L494). It was working, and nothing changed this side, so I'm guessing this may be a Sauce labs or travis issue that will be resolved.

**Comment by douglasduteil** [comment]
Isn't it because you disabled it ?
https://github.com/ModuleLoader/es6-module-loader/blob/a7ce149a431a84eef27f8c36c54c372edb1b56c5/karma.conf.js#L109

**Comment by guybedford** [comment]
Haha! Ok that would explain it. But then why would it still be trying to run it?

**Comment by guybedford** [comment]
Ahh, it seems this was caused by the matrix PR. I've commented them out for now.

**Comment by guybedford** [comment]
This is so strange, now there's another random error - https://travis-ci.org/ModuleLoader/es6-module-loader/jobs/50191819#L103.

**Comment by douglasduteil** [comment]
Yeah Travis CI some times...
Just refresh
hero img png 2000x1052
 it

**Comment by douglasduteil** [comment]
Yeah Travis CI some times...
Just refresh it

hero img png 2000x1052

**Comment by guybedford** [comment]
Thanks! Tried three times but still not working. Will wait and see if it just needs some time.

**Comment by douglasduteil** [comment]
... Did you tried without npm update ?

**Comment by guybedford** [comment]
I tried in https://github.com/ModuleLoader/es6-module-loader/commit/0b63565ddf006a1b8b791d61c47c1e1604b6c143 but it's still erroring.

**Comment by guybedford** [comment]
Actually it's a test failure now. I'll look into it.

**Pull request merged**
