### PR TITLE
test: fix ie9 console.log error

### PR DESCRIPTION
**Pull request by douglasduteil**
On SauceLabs the instantiated IE browser can be available without developer tools opened.
And for IE 8-9 it means no "console" object defined on window...

### CODE REVIEW

**Comment by guybedford** [comment]
Why would we want to set `console.log` to alert? Surely we should use something non-blocking?

**Comment by guybedford** [comment]
@douglasduteil shouldn't this build failure be reporting the whole build as a failure https://travis-ci.org/ModuleLoader/es6-module-loader/jobs/48320315#L473 ?

**Comment by douglasduteil** [comment]
> Why would we want to set console.log to alert? Surely we should use something non-blocking?

K. I set to alert to make sure IE was responding to the logs in the tests...
Sry for the tests I forgot to test on node yesterday...

Anyway. What you think about using the [`window.dump`](https://developer.mozilla.org/en-US/docs/Web/API/window.dump) or an empty function if no console.log exist ?

**Comment by guybedford** [comment]
An empty function seems fine.

Let me know about that other point when you can too.

**Comment by douglasduteil** [comment]
:up:

**Comment by douglasduteil** [comment]
Rocks here : https://travis-ci.org/douglasduteil/es6-module-loader/jobs/48323469#L401

**Comment by guybedford** [comment]
Nice! I'd still be very interested to hear why the issue above wasn't returning a full build failure though? How could a failing test result in a passing build?

**Comment by douglasduteil** [comment]
Ha !  I forgot to say it.

If you're looking at the [Travis output of this repo](https://travis-ci.org/ModuleLoader/es6-module-loader/jobs/48323472#L422) you'll notice the saucelabs auth always fails. 
It's because my code expect the saucelab username and access key to be exposed in the env (see https://github.com/ModuleLoader/es6-module-loader/pull/284#issuecomment-71205837).

So when I made my PR #284, I told Travis to [run the saucelabs tests out of the script command](https://github.com/ModuleLoader/es6-module-loader/pull/284/files#diff-354f30a63fb0907d4ad57269548329e3R19). So Travis will run them but their outputs wouldn't be taken into account (see [Travis Build Lifecycle](http://docs.travis-ci.com/user/build-configuration/#Build-Lifecycle)) like it will continue to fail as long as the authentication is not valid.

**Comment by guybedford** [comment]
@douglasduteil ok right, thanks for explaining! So we can switch this back then?

**Comment by douglasduteil** [comment]
> So we can switch this back then?

what "this" ?

**Comment by douglasduteil** [comment]
The saucelabs test ?

**Comment by guybedford** [comment]
Move these statements into script?

https://github.com/ModuleLoader/es6-module-loader/blob/master/.travis.yml#L20

**Comment by douglasduteil** [comment]
You will need to expose the `SAUCE_USERNAME` and the `SAUCE_ACCESS_KEY` on the Travis environment first see [douglasduteil/dummy-fuzzy-batman#note-to-make-it-work](https://github.com/douglasduteil/dummy-fuzzy-batman#note-to-make-it-work)

**Comment by guybedford** [comment]
Right, yes I've done that.

**Comment by douglasduteil** [comment]
Alright then we're good :)
Move the lines and Ship It ! :shipit:

**Comment by guybedford** [comment]
Great thanks, I've included them.

**Comment by douglasduteil** [comment]
It's looking good :+1:

**Pull request merged**
