### PR TITLE
Remove site object from System

### PR DESCRIPTION
**Pull request by probins**
something like this can be put back in as and when the spec gets around to defining it.

### CODE REVIEW

**Comment by probins** [comment]
tests are using System.site too. Looks like there's quite a lot of changes needed to the test suite to get it in line with the new spec.

**Comment by guybedford** [comment]
Let's remove the sites tests then? Or perhaps move the implementation of `sites` into a hook in the tests if the tests rely on it too heavily?

**Comment by probins** [comment]
the tests are currently using `site.` for 2 things: in `system.normalize.spec.js`, and to set `babel` and `traceur` locations. As both of these have to be changed anyway (`normalize` no longer exists, and Babel has to change for Babel 6 - if we decide to go with a special build with only import/export transpile, then package.json will have to be changed to reflect that), I don't see much point in doing anything to the tests atm. ISTM the better approach is to decide first what needs to be done to match the polyfill to the spec and the new environment (such as Babel/Traceur), and to ignore the tests until that's done.

**Comment by probins** [comment]
`site.` is also used by `index.js` for setting path for Babel/Traceur

**Comment by probins** [comment]
might as well close this for the moment as well

**Pull request closed without merging**
